apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.azDeploy }}
  labels:
    app: {{ .Values.azApp }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.azApp }}
  template:
    metadata:
      labels:
        app: {{ .Values.azApp }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}
spec:
  selector:
    app: {{ .Values.azApp }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

